### ISSUE TITLE
Loading documents with Expression interpolation fail

### ISSUE THREAD

**Issue by ArnaudBarre** [ardatan/graphql-toolkit#373]
I try to use a JS constant as a default graphQL variable but it fails (I suppose that the loader expect all interpolations to be fragments injections)

Example:
```ts
const LIMIT = 20;
gql`
  query GetList($limit: Int = ${LIMIT}) {
    id
  }
`
```

Error: `GraphQLError: Syntax Error: Unexpected )`
Stacktrace:
![image](https://user-images.githubusercontent.com/14235743/71015997-cb1ce900-20f4-11ea-9da4-dd4440a3128c.png)

Do you think it will be easy to support that ?
Some of the pagination logic is done is JS and I would like to share the same variable while still benefit from the default parameter

**Comment by ardatan** [comment]
We use [https://github.com/ardatan/graphql-toolkit/tree/master/packages/graphql-tag-pluck](graphql-tag-pluck) without evaluating that value which is needed in your case. It just extracts GraphQL definitions from a code file. `${LIMIT}` is considered invalid because it extracts it like below;
```gql
query GetList($limit: Int = ${LIMIT}) {
    id
  }
```
If we try to support this case, we would need to run the code which can be unwanted side effects because that code file may contain more stuff that we don't want to execute besides the query part.
